#!/usr/bin/env node
/**
 * Current-state view: curated pulse + locked baseline link + ADR roll-up + hub snapshot.
 *
 * Composed of:
 *   1. Pulse — full body of [[pulse]], the curated narrative
 *   2. Baseline — link to [[yap-baseline]], the locked pre-z-yap snapshot
 *   3. ADRs — roll-up of accepted ADRs with implementation-state tally
 *   4. Hub snapshot — per `hub` zettel: members grouped by epistemic status
 *
 * Usage:
 *   node scripts/current-state.js              # ANSI
 *   node scripts/current-state.js --markdown   # writes dist/CURRENT-STATE.md
 *   node scripts/current-state.js --detail     # expand each hub member listing
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { loadAll, byTag, parseConnections, edgesFor, bySlug } from "./lib/parse.js";
import { loadAdrs, EPISTEMIC_TAGS_LIST } from "./lib/adrs.js";
import { c } from "./lib/colors.js";

const args = process.argv.slice(2);
const markdown = args.includes("--markdown");
const detail = args.includes("--detail");

const zettels = loadAll();
const slugIndex = bySlug(zettels);
const edges = parseConnections();

const pulse = slugIndex["pulse"];
const baseline = slugIndex["yap-baseline"];
const adrs = loadAdrs(zettels, edges);
const hubs = byTag(zettels, "hub").filter((h) => h.slug !== "pulse" && h.slug !== "yap-baseline");

const epistemicOf = (z) => z.tags.find((t) => EPISTEMIC_TAGS_LIST.includes(t)) ?? null;

const hubSnapshot = hubs.map((h) => {
  const { outgoing } = edgesFor(h.slug, edges);
  const members = outgoing
    .filter((e) => e.label === "INCLUDES")
    .map((e) => slugIndex[e.target])
    .filter(Boolean);

  const buckets = { implemented: [], "in-progress": [], planned: [], other: [] };
  for (const m of members) {
    const k = epistemicOf(m);
    if (k === "implemented") buckets.implemented.push(m);
    else if (k === "in-progress" || k === "incomplete") buckets["in-progress"].push(m);
    else if (k === "planned" || k === "speculative") buckets.planned.push(m);
    else buckets.other.push(m);
  }
  return { hub: h, members, buckets };
});

const adrRollup = adrs.map((a) => {
  const impl = a.trackedIn.filter((e) => e.label === "IMPLEMENTS");
  const documented = a.trackedOut.filter((e) => e.label === "DOCUMENTS");
  const motivated = a.trackedOut.filter((e) => e.label === "MOTIVATES");
  const allTracked = [...impl.map((e) => e.zettel), ...documented.map((e) => e.zettel), ...motivated.map((e) => e.zettel)].filter(Boolean);
  const counts = { implemented: 0, "in-progress": 0, planned: 0, other: 0 };
  for (const z of allTracked) {
    const k = epistemicOf(z);
    if (k === "implemented") counts.implemented++;
    else if (k === "in-progress" || k === "incomplete") counts["in-progress"]++;
    else if (k === "planned" || k === "speculative") counts.planned++;
    else counts.other++;
  }
  return { adr: a, trackedTotal: allTracked.length, counts };
});

if (markdown) {
  writeMarkdown();
} else {
  printAnsi();
}

function writeMarkdown() {
  const lines = [];

  lines.push("# Current state");
  lines.push("");
  lines.push("> Generated by `scripts/current-state.js --markdown`.");
  lines.push("> Pulse is curated; everything below is derived from the graph.");
  lines.push("");

  if (pulse) {
    lines.push("## Pulse");
    lines.push("");
    lines.push(pulseBody());
    lines.push("");
  }

  lines.push("## Baseline");
  lines.push("");
  if (baseline) {
    lines.push(`Pre-z-yap state lives in [[${baseline.slug}]] (locked snapshot, tagged \`frozen\`).`);
    const para = firstParagraph(baseline.body);
    if (para) lines.push("", `> ${para}`);
  } else {
    lines.push("_(No `yap-baseline` zettel found.)_");
  }
  lines.push("");

  lines.push("## Architectural decisions");
  lines.push("");
  lines.push("| ADR | Title | Lifecycle | Tracked | Implemented | In-progress | Planned |");
  lines.push("|-----|-------|-----------|---------|-------------|-------------|---------|");
  for (const { adr, trackedTotal, counts } of adrRollup) {
    lines.push(`| ${adr.id ?? "?"} | ${adr.title} | ${adr.lifecycle ?? "—"} | ${trackedTotal} | ${counts.implemented} | ${counts["in-progress"]} | ${counts.planned} |`);
  }
  lines.push("");

  lines.push("## Hub snapshot");
  lines.push("");
  for (const { hub, members, buckets } of hubSnapshot) {
    if (members.length === 0) continue;
    const tally = `${buckets.implemented.length} done / ${buckets["in-progress"].length} active / ${buckets.planned.length} planned / ${buckets.other.length} other`;
    lines.push(`### ${hub.title} (${tally})`);
    lines.push("");
    lines.push(`Hub: [[${hub.slug}]]`);
    lines.push("");

    if (detail) {
      for (const [label, list] of Object.entries(buckets)) {
        if (list.length === 0) continue;
        lines.push(`**${label}** (${list.length}):`);
        for (const m of list.sort((a, b) => a.title.localeCompare(b.title))) {
          lines.push(`- [[${m.slug}]] — ${m.title}`);
        }
        lines.push("");
      }
    }
  }

  const ROOT = join(import.meta.dirname, "..");
  const distDir = join(ROOT, "dist");
  mkdirSync(distDir, { recursive: true });
  const outPath = join(distDir, "CURRENT-STATE.md");
  writeFileSync(outPath, lines.join("\n"));
  console.log(`  Wrote ${outPath}`);
}

function printAnsi() {
  console.log(`\n${c.bold}z-yap Current State${c.reset}`);
  console.log("─".repeat(64));

  if (pulse) {
    console.log(`\n${c.bold}${c.cyan}Pulse${c.reset}  ${c.gray}[[${pulse.slug}]]${c.reset}\n`);
    console.log(pulseBody());
  }

  if (baseline) {
    console.log(`\n${c.bold}${c.cyan}Baseline${c.reset}  ${c.gray}[[${baseline.slug}]]${c.reset}`);
    const para = firstParagraph(baseline.body);
    if (para) console.log(`  ${c.gray}${para}${c.reset}`);
  }

  console.log(`\n${c.bold}${c.cyan}Architectural Decisions${c.reset}\n`);
  const idW = 6;
  const titleW = Math.max(5, ...adrRollup.map((r) => r.adr.title.length));
  const lifeW = 11;
  console.log(`  ${pad("ID", idW)}  ${pad("Title", titleW)}  ${pad("Lifecycle", lifeW)}  Tracked  Done  Active  Planned`);
  console.log(`  ${"─".repeat(idW)}  ${"─".repeat(titleW)}  ${"─".repeat(lifeW)}  ───────  ────  ──────  ───────`);
  for (const { adr, trackedTotal, counts } of adrRollup) {
    console.log(
      `  ${c.cyan}${pad(adr.id ?? "—", idW)}${c.reset}  ` +
      `${pad(adr.title, titleW)}  ` +
      `${pad(adr.lifecycle ?? "—", lifeW)}  ` +
      `${rpad(trackedTotal, 7)}  ` +
      `${rpad(counts.implemented, 4)}  ` +
      `${rpad(counts["in-progress"], 6)}  ` +
      `${rpad(counts.planned, 7)}`
    );
  }

  console.log(`\n${c.bold}${c.cyan}Hub Snapshot${c.reset}\n`);
  for (const { hub, members, buckets } of hubSnapshot) {
    if (members.length === 0) continue;
    const tally =
      `${c.green}${buckets.implemented.length}${c.reset} done / ` +
      `${c.cyan}${buckets["in-progress"].length}${c.reset} active / ` +
      `${c.yellow}${buckets.planned.length}${c.reset} planned / ` +
      `${c.gray}${buckets.other.length}${c.reset} other`;
    console.log(`  ${c.bold}${hub.title}${c.reset}  ${c.gray}[[${hub.slug}]]${c.reset}`);
    console.log(`    ${tally}`);

    if (detail) {
      for (const [label, list] of Object.entries(buckets)) {
        if (list.length === 0) continue;
        const items = list.sort((a, b) => a.title.localeCompare(b.title)).map((m) => m.title).slice(0, 10);
        console.log(`    ${c.gray}${label}:${c.reset} ${items.join(", ")}${list.length > 10 ? c.gray + ` (+${list.length - 10})` + c.reset : ""}`);
      }
    }
    console.log();
  }
}

function pulseBody() {
  if (!pulse) return "_(No `pulse` zettel found.)_";
  return pulse.body.replace(/^#\s+.+\n+/, "").trim();
}

function firstParagraph(body) {
  const stripped = body.replace(/^#\s+.+\n+/, "");
  const paragraphs = stripped.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  return paragraphs[0] ?? null;
}

function pad(s, n) { return String(s).padEnd(n); }
function rpad(s, n) { return String(s).padStart(n); }
